### ISSUE TITLE
EVU Einspeisung Schriftfarbe

### ISSUE THREAD

**Issue by oRudi07** [etnie83/OpenWB_Display_Large#4]
Die Schriftfarbe bei Einspeisung (EVU) sollte eigentlich grün werden (negative Zahl).
Die Farbe bleibt aber rot, egal ob Einspeisung oder Bezug.

**Comment by etnie83** [comment]
Danke für den Hinweis. Hab ich gestern Abend bei der Überarbeitung für OpenWB2.0 auch bemerkt ist aber aktuell noch falsch im Master-Branch-Code.
In Zeile 420 & 424 muss "EVU_dir"  geändert werden zu "EVU_dir [0]"
Da wird das Array nicht richtig abgefragt. Lade nachher das Update für die Integration mit openWB2.0 Unterstützung hoch da ist es bereits korrigiert.

**Comment by oRudi07** [comment]
Vielen Dank. Habe das auch gerade gefunden :-)
